[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.build]
cmds = [
    "chmod +x ./mvnw",
    "./mvnw clean package -DskipTests"
]

[phases.start]
cmd = "java -Dserver.port=$PORT $JAVA_OPTS -jar target/*.jar"